general.import = [
"~/ghq/github.com/folke/tokyonight.nvim/extras/alacritty/tokyonight_storm.toml"
]

general.live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[window]

opacity = 1
# dimensions = { columns = 140, lines = 33}
# position = { x = 200, y = 100}
padding.x = 2
# padding.y = 10
# decorations = "None"
decorations_theme_variant = "Dark"

[font]
normal = { family = "FiraCode Nerd Font" }
bold = { family = "FiraCode Nerd Font", style = "Bold"}
italic = { family = "Maple Mono", style = "Italic"}
bold_italic = { family = "Maple Mono", style = "Bold Italic"}
size = 10

[cursor]
thickness = 0.4


# [selection]
# save_to_clipboard = true

[terminal.shell]
program="/usr/bin/fish"
