import = [
"~/.config/alacritty/themes/tokyonight_storm.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[window]

opacity = 1
dimensions = { columns = 140, lines = 33}
position = { x = 200, y = 100}
padding.x = 10
padding.y = 10
decorations = "None"
decorations_theme_variant = "Dark"

[font]
normal = { family = "BlexMono Nerd Font", style = "Medium"} 
bold = { family = "BlexMono Nerd Font", style = "Bold"} 
italic = { family = "BlexMono Nerd Font", style = "Italic"} 
bold_italic = { family = "BlexMono Nerd Font", style = "Bold Italic"} 
size = 12.0


# [selection]
# save_to_clipboard = true

[shell]
program="/usr/bin/fish"
