# Tokyo Night (night) -- https://github.com/folke/tokyonight.nvim
#
# See everforest-dark-hard.conf for what each name is used for.

set -g @thm_bg_dim "#16161e"
set -g @thm_bg_popup "#24283b"
set -g @thm_bg_visual "#3b4261"
set -g @thm_border "#292e42"

set -g @thm_fg "#c0caf5"
set -g @thm_grey "#565f89"
set -g @thm_grey_bright "#787c99"

set -g @thm_accent "#7aa2f7"
set -g @thm_border_active "#3d59a1"

set -g @thm_red "#f7768e"
set -g @thm_orange "#ff9e64"
set -g @thm_yellow "#e0af68"
set -g @thm_aqua "#73daca"
set -g @thm_blue "#7aa2f7"
